# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
services:
    App\EventListener\JWTCreatedListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes controllers in src/Controller available as services
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # makes other classes in src/ available as services
    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
