nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^https://proyecto-final-fp-five\.vercel\.app$']
        allow_credentials: true
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin']
        expose_headers: ['Authorization']
        max_age: 3600

    paths:
        '^/':
            allow_origin: ['^https://proyecto-final-fp-five\.vercel\.app$']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            max_age: 3600
