nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['https://proyecto-final-fp-five.vercel.app']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['https://proyecto-final-fp-five.vercel.app']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            max_age: 3600
